### ISSUE TITLE
remove extra scroll bar in destop mode

### ISSUE THREAD

**Issue by sra1kumar-NULL** [hereiam-solutions/prototype-frontend#104]
https://user-images.githubusercontent.com/62778911/228484193-9109333c-9b53-4242-a2db-c111b3f82cb8.mp4

In mobile browser everything seems fine but in the destop mode an unwanted internal scroll bar or divider is showing up need to remove that

**Comment by mike-kaden** [comment]
There is more to do ;-) It needs an include (meta query) in the styled-components (GlobalStyles and components) for the whole interface, to switch the drawer from bottom to the right side in desktop size. Is that frontend enhancement for you?

**Comment by sra1kumar-NULL** [comment]
> There is more to do ;-) It needs an include (meta query) in the styled-components (GlobalStyles and components) for the whole interface, to switch the drawer from bottom to the right side in desktop size. Is that frontend enhancement for you?

I guess that would be more of a UI Improvement cause many things need to be changed
