### ISSUE TITLE
implement user management

### ISSUE THREAD

**Issue by hereIam-dev** [hereiam-solutions/prototype-frontend#9]
1. Register (id, name, email, password, choose team, pick role, set personal pin, set random alias (2xA-Z), authoritySecret -> prevent users in the wild)
2. Login (name, password, personal pin)
3. Show / Update User Profile (set avatar, switch team, switch role, change password, change personal pin)
4. Logout

**Comment by robinwettstaedt** [comment]
implmented user management through MongoDB Realm
